### ISSUE TITLE
Installation fails because of vcversioner

### ISSUE THREAD

**Issue by gomezgoiri** [gomezgoiri/pt-installation#1]
I have only been able to reproduce this error under the following circumstances.
- Red Hat Enterprise Linux Server release 7.1 (Maipo)
- pip 1.4.1 and 7.1.2
- Behind a proxy, which is configured in environment variables.

```
[user@machine virtualenvdir]$ bin/pip install -e git+https://github.com/gomezgoiri/pt-instances-management.git#egg=ptinstancemanager
Obtaining ptinstancemanager from git+https://github.com/gomezgoiri/pt-instances-management.git#egg=ptinstancemanager
  Updating ./src/ptinstancemanager clone
  Running setup.py egg_info for package ptinstancemanager

(...)

Downloading/unpacking jsonschema>=2.5.1 (from flasgger->ptinstancemanager)
  Downloading jsonschema-2.5.1.tar.gz (50kB): 50kB downloaded
  Running setup.py egg_info for package jsonschema
    Download error on https://pypi.python.org/simple/vcversioner/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!
    Couldn't find index page for 'vcversioner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!
    No local packages or download links found for vcversioner
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/data/user-data/agg96/sss/build/jsonschema/setup.py", line 44, in <module>
        vcversioner={"version_module_paths" : ["jsonschema/_version.py"]},
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/data/user-data/agg96/sss/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/data/user-data/agg96/sss/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/data/user-data/agg96/sss/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('vcversioner')
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/vcversioner/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!

Couldn't find index page for 'vcversioner' (maybe misspelled?)

Download error on https://pypi.python.org/simple/: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!

No local packages or download links found for vcversioner

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/data/user-data/agg96/sss/build/jsonschema/setup.py", line 44, in <module>

    vcversioner={"version_module_paths" : ["jsonschema/_version.py"]},

  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/data/user-data/agg96/sss/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve

    dist = best[req.key] = env.best_match(req, self, installer)

  File "/data/user-data/agg96/sss/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/data/user-data/agg96/sss/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain

    return installer(requirement)

  File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg

    return cmd.easy_install(req)

  File "/data/user-data/agg96/sss/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install

    raise DistutilsError(msg)

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('vcversioner')

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /data/user-data/agg96/sss/build/jsonschema
```

**Comment by gomezgoiri** [comment]
Temporary solution:
- Install _vcversioner_ first:  `$ bin/pip install vcversioner`
- Execute command again:  `$ bin/pip install -e git+https://github.com/gomezgoiri/pt-instances-management.git#egg=ptinstancemanager`

**Comment by gomezgoiri** [comment]
Moved to https://github.com/PTAnywhere/pt-instances-management/issues/3
