### ISSUE TITLE
functools32 not found when executing run-api 

### ISSUE THREAD

**Issue by gomezgoiri** [gomezgoiri/pt-installation#2]
[user@host ~]$ /data/user-data/agg96/ptapi/bin/run-api -createdb -config /data/user-data/agg96/config.ini
Traceback (most recent call last):
  File "/data/user-data/agg96/ptapi/bin/run-api", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(**requires**)
  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/data/user-data/agg96/ptapi/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: functools32

**Comment by gomezgoiri** [comment]
Quick (temporary) solution:
`[user@host ~]]$ /data/user-data/agg96/ptapi/bin/pip install functools32`

**Comment by gomezgoiri** [comment]
Moved to https://github.com/PTAnywhere/pt-instances-management/issues/2

**Comment by gomezgoiri** [comment]
The easiest way to patch this problem is to do it in the installation script.
